### ISSUE TITLE
OAuth Authentication Error

### ISSUE THREAD

**Issue by Kitt3120** [varoOP/shinkro#45]
Hi, I have the following setup:

- shinkro instance behind an nginx reverse proxy using SSL
- Web-UI reachable publicly
- MAL OAuth app created, redirect URL set to https://my.public.domain/malauth/callback

When I start the OAuth flow with my client ID and secret, I get redirected to MAL. I can see my App's description, etc. When I grant access, I am being redirected to my shinkro instance, but the authentication fails. The container only shows the following log when setting to VERBOSE: 

```
shinkro-1  | 2024-05-24 22:55:50 INF Starting shinkro
shinkro-1  | 2024-05-24 22:55:50 INF Version: v0.1.6
shinkro-1  | 2024-05-24 22:55:50 INF Commit: 
shinkro-1  | 2024-05-24 22:55:50 INF Build date: 2024-04-02T00:08:47.899Z
shinkro-1  | 2024-05-24 22:55:50 INF Base URL: /
shinkro-1  | 2024-05-24 22:55:50 INF Log-level: VERBOSE
shinkro-1  | 2024-05-24 22:55:50 TRC Updating anime in database module=database
shinkro-1  | 2024-05-24 22:55:52 TRC Updated anime in database module=database
shinkro-1  | 2024-05-24 22:55:52 INF Starting HTTP server on 0.0.0.0:7011 module=server
shinkro-1  | 2024-05-24 22:56:15 DBG Request processed duration=1.799307 module=server status=200
shinkro-1  | 2024-05-24 22:56:24 DBG Request processed duration=0.098168 module=server status=302
shinkro-1  | 2024-05-24 22:56:32 ERR error="Post \"https://myanimelist.net/v1/oauth2/token\": dial tcp 0.0.0.0:443: connect: connection refused" module=server
shinkro-1  | 2024-05-24 22:56:32 DBG Request processed duration=7.285935 module=server status=303
shinkro-1  | 2024-05-24 22:56:32 DBG Request processed duration=2.533138 module=server status=200

```

My docker-compose.yml:

```
networks:
  shinkro:
    name: shinkro

services:
  shinkro:
    image: ghcr.io/varoop/shinkro:latest
    networks:
      - shinkro
    volumes:
      - ./data:/config
    environment:
      - SHINKRO_USERNAME=<removed>
      - SHINKRO_PASSWORD=<removed>
      - PLEX_USERNAME=<removed>
      - ANIME_LIBRARIES=<removed>
      - PUID=3120
      - PGID=3120
    restart: always
```

My config.toml (Plex connection not set up yet):

```
[shinkro]
Username = "<removed>"
Password = "<removed>"
Host = "0.0.0.0" <- Need this for reverse proxy to work, as the reverse proxy and shinkro are considered different docker machines. But they are in the same docker network "shinkro". So my reverse proxy can all shinkro by its service name, "shinkro".
Port = 7011
ApiKey = "<removed>"
#BaseUrl = "/shinkro"
#DiscordWebhookUrl = ""
LogLevel = "VERBOSE"
LogMaxSize = 50
LogMaxBackups = 3

[plex]
PlexUsername = "<removed>"
AnimeLibraries = ["<removed>"]
#Url = "http://127.0.0.1:32400"
#Token = "<Value of X-Plex-Token>"
```

Am I doing something wrong, or is this a bug?
